# Generated by Django 3.2.9 on 2021-11-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_CarsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('FullName', models.CharField(blank=True, max_length=200, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Типы ТС',
                'verbose_name_plural': 'Тип ТС',
            },
        ),
        migrations.CreateModel(
            name='tb_DevicesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('FullName', models.CharField(blank=True, max_length=200, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Типы оборудования',
                'verbose_name_plural': 'Тип оборудования',
            },
        ),
        migrations.CreateModel(
            name='tb_MarksTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('FullName', models.CharField(blank=True, max_length=200, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Марки ТС',
                'verbose_name_plural': 'Марка ТС',
            },
        ),
        migrations.CreateModel(
            name='tb_Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('FullName', models.CharField(blank=True, max_length=200, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='tb_Produsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('FullName', models.CharField(blank=True, max_length=200, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Производители оборудования',
                'verbose_name_plural': 'Производитель оборудования',
            },
        ),
        migrations.CreateModel(
            name='tb_DevicesMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('tb_DevicesTypes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.tb_devicestypes', verbose_name='Типы устройствТС')),
                ('tb_Produsers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.tb_produsers', verbose_name='Производитель оборудования')),
            ],
            options={
                'verbose_name': 'Марки оборудования',
                'verbose_name_plural': 'Марка оборудования',
            },
        ),
        migrations.CreateModel(
            name='tb_DevicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=100, verbose_name='Наименование')),
                ('tmp', models.CharField(max_length=100, verbose_name='Наименование')),
                ('tb_DevicesMarks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.tb_devicesmarks', verbose_name='Марка оборудования')),
            ],
            options={
                'verbose_name': 'Список устройств',
                'verbose_name_plural': 'Устройство',
            },
        ),
        migrations.CreateModel(
            name='tb_CarsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(blank=True, max_length=20, verbose_name='VIN номер')),
                ('GosNumber', models.CharField(blank=True, max_length=20, verbose_name='Гос номер')),
                ('InventarNumber', models.CharField(blank=True, max_length=30, verbose_name='Инвентарный номер')),
                ('WialonNumber', models.CharField(blank=True, max_length=20, verbose_name='Номер в Виалон')),
                ('tb_CarsTypes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.tb_carstypes', verbose_name='Типы ТС')),
                ('tb_MarksTypes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.tb_markstypes', verbose_name='Марки ТС')),
                ('tb_Organizations_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.tb_organizations', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'ТС',
                'verbose_name_plural': 'Список ТС',
            },
        ),
    ]
