# Generated by Django 3.2.9 on 2021-11-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_deviceslist',
            name='tmp',
        ),
    ]
