# Generated by Django 3.2.9 on 2021-11-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_remove_tb_deviceslist_tmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Список статусов',
                'verbose_name_plural': 'Статус',
            },
        ),
    ]
